### ISSUE TITLE
Wiki Tutorial issue

### ISSUE THREAD

**Issue by myoung34** [puppetlabs/beaker#275]
On the tutorial for writing a module test, there's an issue.

If you use this nodeset:

```
--- 
CONFIG: 
  consoleport: 443 
  nfs_server: none
HOSTS: 
  ubuntu-10-04-4-x64-master: 
    box: ubuntu-server-10044-x64-vbox4210
    box_url: "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-10044-x64-vbox4210.box"
    hypervisor: vagrant
    ip: "192.168.20.20"
    platform: ubuntu-10.04-amd64
    roles: 
      - master
      - agent
      - dashboard
      - database
```

When you run rspec, the command `on host, 'gem install puppet --no-ri --no-rdoc'`, it will fail on the above host with an error about the net/https gemfile missing. The fix is to install libopenssl-ruby. I would make this wiki change, but it wouldn't work for RHEL hosts for sure. But the tutorial does not work as-is and might be confusing to others.
