### ISSUE TITLE
Beaker with private IP is not reachable

### ISSUE THREAD

**Issue by myoung34** [puppetlabs/beaker#581]
My nodeset:

```

---
HOSTS:
  centos-64-x64-vbox4210:
    roles:
      - master
    platform: centos-64-x64-vbox4210
    box: centos-64-x64-vbox4210
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box
    hypervisor: vagrant
    ip: 192.168.56.200
    distmoduledir: /etc/puppet/modules
```

This generates an unreachable VM (ssh timeout) due to HWADDR being set inside that .box (/etc/sysconfig/network-scripts/ifcfg-eth0). The syntax for the generated Vagrantfile is:

```
v.vm.base_mac = 'somerandom'
v.vm.network :private_network, ip: "192.168.56.200", :netmask => "255.255.0.0"
```

According to [this issue](https://github.com/mitchellh/vagrant/issues/3588) the syntax should be:

```
v.vm.network :private_network, ip: "192.168.56.200", :netmask => "255.255.0.0", :mac => 'somerandom'
```

Doing this manually works.
